"""Render the bank and ledger slices of a corpus batch into files that
look like what a finance team actually hands you — not clean exports.

  bank_statement.csv   value_date / narration / debit / credit / balance,
                       running balance, amounts as rupee strings with
                       Indian comma grouping, and the reference buried
                       inside messy free-text narration.

  ledger_export.xlsx   two sheets, each with three junk rows above the
                       real header, dates as DD-MM-YYYY strings, amounts
                       as text with a trailing CR/DR marker.

Deliberately NOT exported: truth_group / is_noise. A real source file has
no answer key. The corpus batch keeps it, joinable back by external_ref.

Usage:
  python -m scripts.export_source_files <batch_id> [out_dir]
"""

import csv
import random
import sys
from datetime import date
from pathlib import Path

from openpyxl import Workbook

from lib import db
from lib.money import paise_to_rupee_string

OUT_DIR = Path(__file__).resolve().parents[1] / "data"

# Narration templates — the reference sits in a different position in
# each, surrounded by real-looking banking noise.
_NARRATION_TEMPLATES = [
    "NEFT/RAZORPAY/{ref}/SETTLEMENT",
    "IMPS/{ref}/RZPY/CR",
    "UPI/{ref}/PAYMENT/REF",
    "NEFT-RAZORPAY-{ref}-SETTLEMENT",
    "TRF FROM RAZORPAY REF {ref} DT {dd}/{mm}",
    "  MPS/{ref}/RAZORPAY SOFTWARE PVT LTD  ",
    "RTGS/{ref}/RAZORPAY/COLLECTION",
    "BY TRANSFER-NEFT*{ref}*RAZORPAY SOFTWARE",
]

_OPENING_BALANCE_PAISE = 5_000_000_00  # ₹50,00,000.00

_rng = random.Random(20260823)


def _page_all(table: str, columns: str, batch_id: str, source_kind: str) -> list[dict]:
    """PostgREST caps a response at 1000 rows, so page explicitly."""
    out: list[dict] = []
    page_size = 1000
    offset = 0
    while True:
        page = db.run_with_retry(
            lambda o=offset: db.get_client()
            .table(table)
            .select(columns)
            .eq("batch_id", batch_id)
            .eq("source_kind", source_kind)
            .order("txn_date")
            .order("external_ref")
            .order("id")
            .range(o, o + page_size - 1)
            .execute()
        ).data
        out.extend(page)
        if len(page) < page_size:
            break
        offset += page_size
    return out


def _fmt_ddmmyyyy(iso: str | None, sep: str) -> str:
    if not iso:
        return ""
    d = date.fromisoformat(iso)
    return f"{d.day:02d}{sep}{d.month:02d}{sep}{d.year}"


def export_bank_csv(rows: list[dict], path: Path) -> int:
    """Write the bank statement. Positive amounts land in credit,
    negative in debit, with a running balance in integer paise rendered
    as a rupee string."""
    balance = _OPENING_BALANCE_PAISE
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["value_date", "narration", "debit", "credit", "balance"])
        for row in rows:
            amount = row["amount_paise"]
            balance += amount

            template = _rng.choice(_NARRATION_TEMPLATES)
            d = date.fromisoformat(row["txn_date"]) if row["txn_date"] else date.today()
            narration = template.format(ref=row["external_ref"], dd=f"{d.day:02d}", mm=f"{d.month:02d}")

            debit = paise_to_rupee_string(amount) if amount < 0 else ""
            credit = paise_to_rupee_string(amount) if amount >= 0 else ""

            writer.writerow([
                _fmt_ddmmyyyy(row["txn_date"], "/"),
                narration,
                debit,
                credit,
                paise_to_rupee_string(balance),
            ])
    return len(rows)


def export_ledger_xlsx(rows: list[dict], path: Path) -> int:
    """Write the ledger across two sheets, each with a three-row junk
    header block above the real header."""
    wb = Workbook()
    wb.remove(wb.active)

    midpoint = len(rows) // 2
    chunks = [("Q1 Ledger", rows[:midpoint]), ("Q2 Ledger", rows[midpoint:])]

    for sheet_name, chunk in chunks:
        ws = wb.create_sheet(title=sheet_name)
        # Three junk rows above the real header, as exported by every
        # accounting package ever.
        ws.append(["ACME COMMERCE PRIVATE LIMITED"])
        ws.append([f"General Ledger Export — {sheet_name}"])
        ws.append(["Generated by FinBooks v4.2", "", "Page 1 of 1"])
        ws.append(["Date", "Voucher No", "Particulars", "Amount"])

        for row in chunk:
            amount = row["amount_paise"]
            marker = "DR" if amount < 0 else "CR"
            ws.append([
                _fmt_ddmmyyyy(row["txn_date"], "-"),
                row["external_ref"],
                f"Ledger entry {row['external_ref']}",
                f"{paise_to_rupee_string(amount)} {marker}",
            ])

    wb.save(path)
    return len(rows)


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        raise SystemExit(1)
    batch_id = sys.argv[1]
    out_dir = Path(sys.argv[2]) if len(sys.argv) > 2 else OUT_DIR
    out_dir.mkdir(parents=True, exist_ok=True)

    cols = "external_ref,amount_paise,txn_date,value_date"
    bank_rows = _page_all("txns", cols, batch_id, "bank")
    ledger_rows = _page_all("txns", cols, batch_id, "ledger")

    bank_path = out_dir / "bank_statement.csv"
    ledger_path = out_dir / "ledger_export.xlsx"

    n_bank = export_bank_csv(bank_rows, bank_path)
    n_ledger = export_ledger_xlsx(ledger_rows, ledger_path)

    print(f"batch_id: {batch_id}")
    print(f"wrote {n_bank} bank rows   -> {bank_path}")
    print(f"wrote {n_ledger} ledger rows -> {ledger_path}")
    return {"bank": n_bank, "ledger": n_ledger, "bank_path": bank_path, "ledger_path": ledger_path}


if __name__ == "__main__":
    main()
